### ISSUE TITLE
EACH FUNCTION PROBLEM

### ISSUE THREAD

**Issue by raj455** [rguedes/PDFMerger#8]
PHP 7.2 not supporting each function..which is in your package...do u have any solution for that

**Comment by rguedes** [comment]
This pull request fix that problem: https://github.com/rguedes/PDFMerger/pull/7

**Comment by larsemil** [comment]
Time for new release with pull request included?

**Comment by eichgi** [comment]
Hi @rguedes we are still waiting for your new release! thx

**Comment by rguedes** [comment]
Hi @eichgi I'm accepting new pull requests, but I'm not maintain the repo.

**Comment by larsemil** [comment]
@rguedes i think what we are asking for is a release 1.0.4 with the pull request #7 included. You dont even have to do anything in the code, just click in github.

**Comment by rguedes** [comment]
Done.

**Comment by eichgi** [comment]
@larsemil it seems the release is launched, but how can I then get the latest version?

**Comment by larsemil** [comment]
if you installed via composer `composer update`  should do the trick.

**Comment by eichgi** [comment]
@larsemil I already execute: composer update rguedes/pdfmerger but I still get the 1.0.3v. Also I tried removing and requiring the package again but I got the same old version, but I notice I am loading from cache, is there another way to force to download the last? I specify 1.0.4v but it fails. thanks!

**Comment by rguedes** [comment]
I'm not control the packagist: https://packagist.org/packages/rguedes/pdfmerger

**Comment by eichgi** [comment]
Anyone else knows how to upload the package on packagist? Or what else could we do?

**Comment by timdiels1** [comment]
I think you need to update your composer.json with the correct tag.
You can see in https://github.com/rguedes/PDFMerger/tree/1.0.4 that the version is set to 1.0.3 and not 1.0.3

Also @rguedes : did you create a packagist account for yourself? It just seems like dot5enko forked your repository and afterwards deleted his repository. I contacted packagist to ask them for help to sort this out. But or he had access to your repository or he pushed his repository with the wrong composer.json where your name was still included.

I hope to have an answer soon from packagist. In meanwhile, i forked your repository and will create own package as the need for the update is urgent.

**Comment by rguedes** [comment]
@timdiels1 composer updated, thx for the tip :D
Yes, i have an account and yes, he pushed his repository with my composer.json

**Comment by timdiels1** [comment]
Ok just tested this and as there was no package of you as vendor, he was able to submit the package to packagist in your name as he did not change the composer.json
Let's hope packagist can help us out now.
I'm not creating a package as i hope this will be sorted out soon.
My solution for now is using a vcs repository in composer.json

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rguedes/PDFMerger"
        }
    ],
    "require": {
        "rguedes/PDFMerger": "1.0.4"
    }
}
```

**Comment by Seldaek** [comment]
Hey, I transferred the package to @rguedes - note that the package is currently in a broken state due to an invalid license:

> Skipped branch master, Invalid package information: 
> License "LGPL" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.

You probably want to use `LGPL-3.0-or-later` or something similar.

**Comment by timdiels1** [comment]
Damn they are fast! Ok @rguedes let's get this sorted ;)

**Comment by timdiels1** [comment]
Pull request ready https://github.com/rguedes/PDFMerger/pull/13

**Comment by larsemil** [comment]
@rguedes Could you please add a new release in github, and then close this? 

If you want help to maintain this repository I can gladly help.

**Comment by larsemil** [comment]
Closing this as all merge requests from this thread are merged and issue is solved.
